# Generated by Django 3.0 on 2021-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
